/*
  Copyright (c) 2019 Qualcomm Technologies, Inc.
  All Rights Reserved.
  Confidential and Proprietary - Qualcomm Technologies, Inc.
*/

BEGIN TRANSACTION;

INSERT OR REPLACE INTO qcril_properties_table (property, value) VALUES ('qcrildb_version', 24);

DELETE FROM qcril_emergency_source_mcc_mnc_table   where MCC = '716' AND MNC = '17' AND NUMBER = "105" ;
DELETE FROM qcril_emergency_source_mcc_table   where MCC = '410'  AND NUMBER = '117';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '410'  AND NUMBER = '117';

DELETE FROM qcril_emergency_source_mcc_table     where MCC = '206' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '206' AND NUMBER = '112';
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('206','911','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('206','112','','');
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '228' AND NUMBER = '112';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '228' AND NUMBER = '911';
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('228','112','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('228','911','','');
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '230' AND NUMBER = '911';
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('230','911','','');
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '410' AND NUMBER = '1122';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '410' AND NUMBER = '130';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '424' AND NUMBER = '999';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '424' AND NUMBER = '991';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '424' AND NUMBER = '992';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '424' AND NUMBER = '993';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '424' AND NUMBER = '995';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '424' AND NUMBER = '996';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '424' AND NUMBER = '997';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '424' AND NUMBER = '998';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '424' AND NUMBER = '901';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '424' AND NUMBER = '909';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '424' AND NUMBER = '116111';

DELETE FROM qcril_emergency_source_mcc_table     where MCC = '427' AND NUMBER = '112';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '427' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '427' AND NUMBER = '999';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '427' AND NUMBER = '135';
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('427','112','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('427','911','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('427','999','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('427','135','','');
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '455' AND NUMBER = '993';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '455' AND NUMBER = '110';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '455' AND NUMBER = '119';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '455' AND NUMBER = '120';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '457' AND NUMBER = '1199';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '505' AND NUMBER = '112';
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('505','112','','');
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '639' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '639' AND NUMBER = '112';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '639' AND NUMBER = '999';
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('639','911','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('639','112','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('639','999','','');
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '714' AND NUMBER = '103';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '714' AND NUMBER = '105';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '714' AND NUMBER = '106';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '714' AND NUMBER = '107';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '714' AND NUMBER = '108';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '714' AND NUMBER = '109';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '714' AND NUMBER = '133';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '714' AND NUMBER = '141';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '714' AND NUMBER = '155';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '714' AND NUMBER = '311';

DELETE FROM qcril_emergency_source_mcc_table     where MCC = '551' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '466' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '466' AND NUMBER = '112';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '340' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '340' AND NUMBER = '112';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '647' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '647' AND NUMBER = '112';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '208' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '208' AND NUMBER = '112';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '370' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '370' AND NUMBER = '112';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '434' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '434' AND NUMBER = '112';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '216' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '286' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '255' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '255' AND NUMBER = '112';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '260' AND NUMBER = '122';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '422' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '238' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '238' AND NUMBER = '112';
DELETE FROM qcril_emergency_source_mcc_table     where MCC = '604' AND NUMBER = '112';
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('551','911','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('466','911','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('466','112','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('340','911','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('340','112','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('647','911','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('647','112','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('208','911','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('208','112','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('370','911','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('370','112','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('434','911','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('434','112','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('216','911','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('286','911','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('255','112','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('255','911','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('260','122','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('422','911','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('238','911','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('238','112','','');
INSERT INTO "qcril_emergency_source_mcc_table" VALUES('604','112','','');
DELETE FROM qcril_emergency_source_voice_table   where MCC = '280'  AND NUMBER = '199';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '410'  AND NUMBER = '1122';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '410'  AND NUMBER = '130';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '410'  AND NUMBER = '114';
INSERT INTO "qcril_emergency_source_voice_table" VALUES('410','114','','full');
DELETE FROM qcril_emergency_source_voice_table   where MCC = '424'  AND NUMBER = '991';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '424'  AND NUMBER = '992';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '424'  AND NUMBER = '993';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '424'  AND NUMBER = '995';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '424'  AND NUMBER = '996';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '424'  AND NUMBER = '997';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '424'  AND NUMBER = '998';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '424'  AND NUMBER = '901';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '424'  AND NUMBER = '909';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '424'  AND NUMBER = '116111';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '457'  AND NUMBER = '1199';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '457'  AND NUMBER = '1196';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '457'  AND NUMBER = '1168';
INSERT INTO "qcril_emergency_source_voice_table" VALUES('457','1196','','full');
INSERT INTO "qcril_emergency_source_voice_table" VALUES('457','1168','','full');
DELETE FROM qcril_emergency_source_voice_table   where MCC = '604'  AND NUMBER = '19';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '604'  AND NUMBER = '15';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '604'  AND NUMBER = '177';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '604'  AND NUMBER = '150';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '604'  AND NUMBER = '190';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '466'  AND NUMBER = '110';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '466'  AND NUMBER = '119';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '466'  AND NUMBER = '118';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '286'  AND NUMBER = '110';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '286'  AND NUMBER = '155';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '255'  AND NUMBER = '101';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '255'  AND NUMBER = '102';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '255'  AND NUMBER = '103';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '260'  AND NUMBER = '123';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '260'  AND NUMBER = '180';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '260'  AND NUMBER = '126';
DELETE FROM qcril_emergency_source_voice_table   where MCC = '422'  AND NUMBER = '9999';
INSERT INTO "qcril_emergency_source_voice_table" VALUES('466','110','','full');
INSERT INTO "qcril_emergency_source_voice_table" VALUES('466','119','','full');
INSERT INTO "qcril_emergency_source_voice_table" VALUES('466','118','','full');
INSERT INTO "qcril_emergency_source_voice_table" VALUES('286','110','','full');
INSERT INTO "qcril_emergency_source_voice_table" VALUES('286','155','','full');
INSERT INTO "qcril_emergency_source_voice_table" VALUES('255','101','','full');
INSERT INTO "qcril_emergency_source_voice_table" VALUES('255','102','','full');
INSERT INTO "qcril_emergency_source_voice_table" VALUES('255','103','','full');
INSERT INTO "qcril_emergency_source_voice_table" VALUES('260','123','','full');
INSERT INTO "qcril_emergency_source_voice_table" VALUES('260','180','','full');
INSERT INTO "qcril_emergency_source_voice_table" VALUES('260','126','','full');
INSERT INTO "qcril_emergency_source_voice_table" VALUES('422','9999','','full');
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '206'  AND NUMBER = '000';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '206'  AND NUMBER = '08';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '206'  AND NUMBER = '110';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '206'  AND NUMBER = '118';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '206'  AND NUMBER = '119';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '206'  AND NUMBER = '911';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '206'  AND NUMBER = '999';
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('206','000','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('206','08','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('206','110','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('206','118','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('206','119','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('206','911','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('206','999','','');
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '222'  AND NUMBER = '000';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '222'  AND NUMBER = '08';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '222'  AND NUMBER = '110';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '222'  AND NUMBER = '118';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '222'  AND NUMBER = '119';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '222'  AND NUMBER = '911';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '222'  AND NUMBER = '999';
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('222','000','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('222','08','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('222','110','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('222','118','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('222','119','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('222','911','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('222','999','','');
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '230'  AND NUMBER = '000';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '230'  AND NUMBER = '08';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '230'  AND NUMBER = '110';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '230'  AND NUMBER = '118';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '230'  AND NUMBER = '119';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '230'  AND NUMBER = '911';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '230'  AND NUMBER = '999';
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('230','000','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('230','08','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('230','110','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('230','118','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('230','119','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('230','911','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('230','999','','');
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '238'  AND NUMBER = '911';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '238'  AND NUMBER = '112';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '238'  AND NUMBER = '000';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '238'  AND NUMBER = '08';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '238'  AND NUMBER = '110';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '238'  AND NUMBER = '118';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '238'  AND NUMBER = '119';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '238'  AND NUMBER = '999';
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('238','911','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('238','112','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('238','000','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('238','08','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('238','110','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('238','118','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('238','119','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('238','999','','');
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '272'  AND NUMBER = '1913';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '272'  AND NUMBER = '911';
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('272','911','','');
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '280'  AND NUMBER = '199';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '370'  AND NUMBER = '911';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '370'  AND NUMBER = '112';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '370'  AND NUMBER = '000';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '370'  AND NUMBER = '08';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '370'  AND NUMBER = '110';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '370'  AND NUMBER = '118';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '370'  AND NUMBER = '119';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '370'  AND NUMBER = '999';
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('370','911','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('370','112','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('370','000','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('370','08','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('370','110','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('370','118','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('370','119','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('370','999','','');
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '427'  AND NUMBER = '112';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '427'  AND NUMBER = '911';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '427'  AND NUMBER = '999';
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('427','112','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('427','911','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('427','999','','');
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '455'  AND NUMBER = '120';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '455'  AND NUMBER = '993';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '505'  AND NUMBER = '000';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '505'  AND NUMBER = '112';
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('505','000','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('505','112','','');
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '639'  AND NUMBER = '999';
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('639','999','','');
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '714'  AND NUMBER = '104';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '722'  AND NUMBER = '100';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '722'  AND NUMBER = '107';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '748'  AND NUMBER = '000';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '748'  AND NUMBER = '08';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '748'  AND NUMBER = '110';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '748'  AND NUMBER = '118';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '748'  AND NUMBER = '119';
DELETE FROM qcril_emergency_source_hard_mcc_table   where MCC = '748'  AND NUMBER = '999';
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('748','000','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('748','08','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('748','110','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('748','118','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('748','119','','');
INSERT INTO "qcril_emergency_source_hard_mcc_table" VALUES('748','999','','');
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '340' AND MNC = '01' AND NUMBER = '112';
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '340' AND MNC = '01' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '440' AND MNC = '51' AND NUMBER = '184110';
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '440' AND MNC = '51' AND NUMBER = '184118';
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '440' AND MNC = '51' AND NUMBER = '184119';
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '440' AND MNC = '51' AND NUMBER = '186110';
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '440' AND MNC = '51' AND NUMBER = '186118';
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '440' AND MNC = '51' AND NUMBER = '186119';
INSERT INTO "qcril_emergency_source_mcc_mnc_table" VALUES('440','51','184110','','');
INSERT INTO "qcril_emergency_source_mcc_mnc_table" VALUES('440','51','184118','','');
INSERT INTO "qcril_emergency_source_mcc_mnc_table" VALUES('440','51','184119','','');
INSERT INTO "qcril_emergency_source_mcc_mnc_table" VALUES('440','51','186110','','');
INSERT INTO "qcril_emergency_source_mcc_mnc_table" VALUES('440','51','186118','','');
INSERT INTO "qcril_emergency_source_mcc_mnc_table" VALUES('440','51','186119','','');
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '647' AND MNC = '00' AND NUMBER = '112';
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '647' AND MNC = '00' AND NUMBER = '911';
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '722' AND MNC = '07' AND NUMBER = '100';
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '722' AND MNC = '07' AND NUMBER = '102';
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '722' AND MNC = '07' AND NUMBER = '105';
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '722' AND MNC = '07' AND NUMBER = '106';
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '722' AND MNC = '07' AND NUMBER = '107';
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '748' AND MNC = '10' AND NUMBER = '104';
DELETE FROM qcril_emergency_source_mcc_mnc_table    where MCC = '748' AND MNC = '10' AND NUMBER = '112';
INSERT INTO "qcril_emergency_source_mcc_mnc_table" VALUES('748','10','112','','');
DELETE FROM qcril_emergency_source_voice_mcc_mnc_table    where MCC = '230' AND MNC = '01' AND NUMBER = '150';
DELETE FROM qcril_emergency_source_voice_mcc_mnc_table    where MCC = '230' AND MNC = '01' AND NUMBER = '155';
DELETE FROM qcril_emergency_source_voice_mcc_mnc_table    where MCC = '230' AND MNC = '01' AND NUMBER = '158';
INSERT INTO "qcril_emergency_source_voice_mcc_mnc_table" VALUES('230','01','150','','');
INSERT INTO "qcril_emergency_source_voice_mcc_mnc_table" VALUES('230','01','155','','');
INSERT INTO "qcril_emergency_source_voice_mcc_mnc_table" VALUES('230','01','158','','');
DELETE FROM qcril_emergency_source_voice_mcc_mnc_table    where MCC = '452' AND MNC = '05' AND NUMBER = '113';
DELETE FROM qcril_emergency_source_voice_mcc_mnc_table    where MCC = '452' AND MNC = '05' AND NUMBER = '114';
DELETE FROM qcril_emergency_source_voice_mcc_mnc_table    where MCC = '452' AND MNC = '05' AND NUMBER = '115';
DELETE FROM qcril_emergency_source_voice_mcc_mnc_table    where MCC = '722' AND MNC = '07' AND NUMBER = '100';
DELETE FROM qcril_emergency_source_voice_mcc_mnc_table    where MCC = '722' AND MNC = '07' AND NUMBER = '102';
DELETE FROM qcril_emergency_source_voice_mcc_mnc_table    where MCC = '722' AND MNC = '07' AND NUMBER = '105';
DELETE FROM qcril_emergency_source_voice_mcc_mnc_table    where MCC = '722' AND MNC = '07' AND NUMBER = '106';
DELETE FROM qcril_emergency_source_voice_mcc_mnc_table    where MCC = '722' AND MNC = '07' AND NUMBER = '107';

COMMIT TRANSACTION;
